[package]
name = "nadylib"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3"
lazy_static = { version = "1.4", optional = true }
leaky-bucket = "0.10"
log = "0.4"
num-bigint = { version = "0.3", features = ["rand"] }
num-traits = "0.2"
num_enum = "0.5"
rand = "0.7"
regex = { version = "1.4", default-features = false, features = ["std", "unicode-perl"], optional = true }
serde_json = { version = "1.0", optional = true }
strfmt = { version = "0.1", optional = true }
tokio = { version = "1.0", default-features = false, features = ["net", "rt", "io-util", "time", "sync"] }

[features]
default = ["mmdb"]
mmdb-parser = []
mmdb = ["serde_json", "lazy_static", "regex", "strfmt"]
