[package]
name = "nadylib"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
byteorder = "1.4"
leaky-bucket = { git = "https://github.com/Gelbpunkt/leaky-bucket.git", branch = "main" }
log = "0.4"
num-bigint = { version = "0.3", features = ["rand"] }
num-traits = "0.2"
num_enum = "0.5"
rand = "0.8"
tokio = { version = "1.0", default-features = false, features = [
    "net",
    "rt",
    "io-util",
    "time",
    "sync"
] }

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = [
    "net",
    "rt",
    "io-util",
    "time",
    "sync",
    "rt-multi-thread",
    "macros"
] }

[patch.crates-io]
# num-bigint is on rand 0.7, see https://github.com/rust-num/num-bigint/pull/185
num-bigint = { git = "https://github.com/Gelbpunkt/num-bigint.git", branch = "rand-0.8", features = [
    "rand"
] }

[features]
default = ["mmdb"]
mmdb-parser = []
mmdb = []
