[package]
name = "nadylib"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
byteorder = "1.4"
leaky-bucket-lite = "0.1.0"
log = "0.4"
num-bigint = { version = "0.3", default-features = false }
num-traits = "0.2"
getrandom = "0.2"
tokio = { version = "1.0", default-features = false, features = [
    "net",
    "rt",
    "io-util",
    "time",
    "sync"
] }

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = [
    "net",
    "rt",
    "io-util",
    "time",
    "sync",
    "rt-multi-thread",
    "macros"
] }

[features]
default = ["mmdb"]
mmdb-parser = []
mmdb = []
