name: Build binaries

on:
  push:
    branches:
      - unstable
      - stable
    tags:
      - '*'
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/aochatproxy aochatproxy-linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aochatproxy-linux
          path: |
            aochatproxy-linux

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/aochatproxy aochatproxy-macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aochatproxy-macos
          path: |
            aochatproxy-macos

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          cp target/release/aochatproxy.exe aochatproxy-windows.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aochatproxy-windows
          path: |
            aochatproxy-windows.exe
